name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.11'  # Specify the Terraform version you want to use

    - name: Terraform Initialization
      run: terraform init
      env:
        TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # GitHub Secret for the Terraform Cloud API Token

    - name: Terraform Plan
      run: terraform plan
      env:
        TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # GitHub Secret for the Terraform Cloud API Token

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # GitHub Secret for the Terraform Cloud API Token
