name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.11'

    - name: Terraform Initialization
      run: terraform init
      env:
        TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # Ensure the secret is passed here

    - name: Terraform Plan
      run: terraform plan
      env:
        TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # Ensure the secret is passed here

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TFC_TOKEN: ${{ secrets.TFC_TOKEN }}  # Ensure the secret is passed here

